### PR TITLE
🐛 Fix release deletion

### LINKED ISSUE #1: It does not delete the release
```
😕  no releases found associated to tag "unstable"
Run dev-drprasad/delete-tag-and-release@v0.1.1
🏷  given tag is "unstable"
✅  unstable deleted successfully!
😕  no releases found associated to tag "unstable"
```

This seems to simply be because it deletes the tag _first_, which forces the GH release to go back into "draft" mode without any tag association.

I think switching the order of these steps should probably resolve it.

### PR DESCRIPTION
**Pull request by bjeanes**
With this change, release is correctly deleted:

```
Run bjeanes/delete-tag-and-release@fix-release-deletion
🏷  given tag is "unstable"
🍻  found 1 releases to delete
👍🏼  all releases deleted successfully!
✅  unstable deleted successfully!
```

GitHub converts a release into draft status when its underlying tag is deleted.

This means that the release deletion code ignored candidate releases for deletion
~both~ because it was a draft (`draft === false`) ~and because it was no longer
associated with any tag~.

Additionally, one of the parameters passed to `fetch()` was incorrect (`url` -> `path`) and its return type was misinterpreted.

Fixes #1

### CODE REVIEW

**Comment by dev-drprasad** [comment]
Thanks for catching the bug and PR!

Since `deleteReleases` and `deleteTag` are both async function, both API requests happen asynchronously. So, we may face race condition. Tag may get deleted before releases and releases will end up in draft state which is, this PR actually trying to solve. To fix this, you can `await`, `deleteReleases` func.

File: index.js [hunk 1]
```diff
@@ -108,4 +106,7 @@ async function run() {
   console.log(`👍🏼  all releases deleted successfully!`);
 }
 
-run();
+if (shouldDeleteRelease) {
+  deleteReleases();
```
Comment (bjeanes) [inline index.js]:
```suggestion
  await deleteReleases();
```

@dev-drprasad do you just mean doing this?

Comment (dev-drprasad) [reply index.js]: I don't think Node12 (used by GitHub actions) has top-level  `async`. we should wrap both `deleteReleases` and `deleteTag` functions in another `async` function or immediately invoked async function

ref: https://flaviocopes.com/javascript-await-top-level/

Comment (bjeanes) [reply index.js]: I've set the PR to allow you to edit my change btw, so feel free to just commit that and merge if that's all it is :)

Comment (bjeanes) [reply index.js]: Interesting. I could wrap the two back in a `main` as you had it originally, but that was not `await`ed either.

File: index.js [hunk 2]
```diff
@@ -108,4 +106,7 @@ async function run() {
...
+}
+deleteTag();
```
Comment (bjeanes) [inline index.js]:
```suggestion
async function run() {	
  if (shouldDeleteRelease) {
    await deleteReleases();
  }
  await deleteTag();
}

run();
```

File: index.js (hunk 1 above)
Comment (dev-drprasad) [reply index.js]: `main` doesn't need to `await`ed. `main` should be `async`, so funcs inside it can be `await`ed

Comment (bjeanes) [reply index.js]: I made a broader suggested change. Let me know if that's what you had in mind.

**Comment by bjeanes** [comment]
Good spot on that race condition! Thanks :)
